module.exports = {
  Svg: "svg",
  Circle: "circle",
  Ellipse: "ellipse",
  G: "g",
  Text: "text",
  TSpan: "tspan",
  TextPath: "textPath",
  Path: "path",
  Polygon: "polygon",
  Polyline: "polyline",
  Line: "line",
  Rect: "rect",
  Use: "use",
  Image: "image",
  Symbol: "symbol",
  Defs: "defs",
  LinearGradient: "linearGradient",
  RadialGradient: "radialGradient",
  Stop: "stop",
  Pattern: "pattern",
  ClipPath: "clipPath",
  Mask: "mask"
};
